{{- if .Values.portal.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "apollo.portal.fullname" . }}
  labels:
    app: {{ template "apollo-helm.name" . }}
    chart: {{ template "apollo-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "{{ .Values.portal.name }}"
spec:
  replicas: {{ .Values.portal.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "apollo-helm.name" . }}
        release: {{ .Release.Name }}
        component: "{{ .Values.portal.name }}"
    spec:
#      serviceAccountName: {{ template "apollo.serviceAccountName.portal" . }}
      containers:
        - name: {{ template "apollo-helm.name" . }}-{{ .Values.portal.name }}
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
          imagePullPolicy: "{{ .Values.portal.image.pullPolicy }}"
          env:
            {{ if .Values.devconfigservice.enabled -}}
            - name: DEV_META
              value: "http://apollo-devconfigservice:8080"
            {{- end }}
            {{ if .Values.fatconfigservice.enabled -}}
            - name: FAT_META
              value: "http://apollo-fatconfigservice:8080"
            {{- end }}
            {{ if .Values.uatconfigservice.enabled -}}
            - name: UAT_META
              value: "http://apollo-uatconfigservice:8080"
            {{- end }}
            {{ if .Values.proconfigservice.enabled -}}
            - name: PRO_META
              value: "http://apollo-proconfigservice:8080"
            {{- end }}
            {{- if .Values.portalmysql.enabled }}
            - name: spring.datasource.url
              value: "jdbc:mysql://apollo-portalmysql:3306/{{ .Values.portalmysql.mysqlDatabase }}?characterEncoding=utf8"
            - name: spring.datasource.username
              value: "{{ .Values.portalmysql.mysqlUser }}"
            - name: spring.datasource.password
              value: "{{ .Values.portalmysql.mysqlPassword }}"
            {{- end }}
            {{- range $key, $value := .Values.portal.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            - containerPort: 8070
          livenessProbe:
            httpGet:
              port: 8070
              path: /
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8070
          resources:
{{ toYaml .Values.portal.resources | indent 12 }}
#          volumeMounts:
#            - name: config-volume
#              mountPath: /apollo-portal-server/config/application-github.properties
#              subPath: application-github.properties
#            - name: config-volume
#              mountPath: /apollo-portal-server/config/apollo-env.properties
#              subPath: apollo-env.properties
    {{- if .Values.portal.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.portal.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.portal.tolerations }}
      tolerations:
{{ toYaml .Values.portal.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.portal.affinity }}
      affinity:
{{ toYaml .Values.portal.affinity | indent 8 }}
    {{- end }}
#      volumes:
#        - name: config-volume
#          configMap:
#            name: {{ if .Values.portal.configMapOverrideName }}{{ .Release.Name }}-{{ .Values.portal.configMapOverrideName }}{{- else }}{{ template "apollo.portal.fullname" . }}{{- end }}
#            items:
#              - key: application-github.properties
#                path: application-github.properties
#              - key: apollo-env.properties
#                path: apollo-env.properties
{{- end }}
